/**
 * scripts/generate_config.js
 * Generates frontend/config.js from environment variables during AWS Amplify build.
 */
const fs = require('fs');
const path = require('path');

const targetPath = path.resolve(__dirname, '..', 'frontend', 'config.js');

const cfg = {
  CONTROL_API_BASE: process.env.CONTROL_API_BASE || '',
  API_KEY: process.env.API_KEY || '',
  TARGET_API_URL: process.env.TARGET_API_URL || '',
  OPERATOR_PASSWORD: process.env.OPERATOR_PASSWORD || ''
};

const fileContent = `/**
 * Fuse Precision Console Configuration
 * Automatically generated by Amplify build from environment variables.
 */

const FUSE_CONFIG = ${JSON.stringify(cfg, null, 2)};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = FUSE_CONFIG;
}
`;

fs.writeFileSync(targetPath, fileContent, 'utf8');
console.log('Successfully generated frontend/config.js:');
console.log(fileContent);
